title: Data Science Study Notes
author: Kelin Zhong
logo: ""

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/KelinZhong/StudyNotes

html:
  use_repository_button: true
  home_page_in_navbar: false

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      navigation_depth: 2
      collapse_navigation: true