title: Data Science Study Notes
author: Kelin Zhong
repository:
  url: https://github.com/KelinZhong/StudyNotes

execute:
  execute_notebooks: "off"

html:
  use_repository_button: true
  home_page_in_navbar: true

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      # Ensures the sidebar is on the left and collapsible
      collapse_navigation: true
      navigation_depth: 3
      show_nav_level: 1
      # Optional: Add a GitHub icon to the top right
      icon_links:
        - name: GitHub
          url: https://github.com/KelinZhong/StudyNotes
          icon: fab fa-github-square